# Autogenerated from websocket_client.template file
import asyncio
import websockets
import json

# This method just sends an arbitrary webSocket message in 'our' format (op and data)
async def send_msg(op, data):
    uri = "ws://127.0.0.1:8080"
    async with websockets.connect(uri) as websocket:
        await websocket.send(json.dumps({"op": op, "data": data}))

        return_val = await websocket.recv()
        # Also, instead of printing the result we return it
        return return_val


async def get_patient_info():
    request = input("Please input patient id: ")
    return await send_msg("get_patient_info", request)


async def get_patient_appointments():
    return await send_msg("get_patient_appointments", '{"doctor_id":"" }')


async def delete_patient():
    return await send_msg("delete_patient", '{"patient_id":"" }')

async def send_presription ():
    request = input("Please input patient id, medicine name and pharmecy name with space inbetween words: ")
    data = request.split()
    json_data = {
            "medicine": data[0],
            "pharmecy": data[1],
            "patient_id": data[2]

        }
    return await send_msg("send_presription", json.dumps(json_data))


async def create_patient():
    patient_ssn = input("Please enter the patients social security number: ")
    patient_name = input("Please enter the patients full name: ")
    patient_address = input("Please enter the patients current address: ")
    patient_phone = input("Please enter the patients current phone number: ")
    patient_email = input("Please enter the patients current email: ")
    patient_record = {}
    data = {"ssn": patient_ssn, "name": patient_name, "address": patient_address, 
    "phone": patient_phone, "email": patient_email, "record": patient_record}
    data = json.dumps(data)
    return await send_msg("create_patient", data)


async def get_patient_list():
    return await send_msg("get_patient_list", '{"doctor_id":"" }')


async def assign_treatment():
    return await send_msg("assign_opperation", "{'doctor_id':'' }")


if __name__ == "__main__":
    # Call each of the generated webSocket methods once and await results.
    print(asyncio.run(get_patient_info()))
    print(asyncio.run(get_patient_appointments()))
    print(asyncio.run(delete_patient()))
    print(asyncio.run(send_presription()))
    print(asyncio.run(create_patient()))
    # print(asyncio.run(get_patient_list()))
